/**
 * Service worker builder.
 *
 * Walks the static export and bakes the asset list into a precache manifest, so
 * the app is genuinely offline from first install rather than only after the
 * user happens to visit each page (PRD 5.6, 12).
 *
 * ponytail: a 40-line post-build script instead of a Workbox/Serwist plugin.
 * There is no build integration to fight with `output: 'export'`, and the
 * caching rules stay readable. Revisit only if the strategy list grows.
 */

import { createHash } from 'node:crypto'
import { readFile, readdir, stat, writeFile } from 'node:fs/promises'
import { join, posix, relative, sep } from 'node:path'

const OUT = 'out'

/**
 * Must match next.config.ts. Empty everywhere except GitHub Pages, which serves
 * a project repo from /<repo>/.
 */
const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? ''

/** Never precache these: the worker itself, and source maps nobody needs offline. */
const SKIP = [/^sw\.js$/, /\.map$/, /^manifest\.webmanifest$/]

async function walk(dir) {
  const found = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) found.push(...(await walk(full)))
    else found.push(full)
  }
  return found
}

const files = await walk(OUT)

const assets = []
let bytes = 0
for (const file of files) {
  const rel = relative(OUT, file).split(sep).join(posix.sep)
  if (SKIP.some((re) => re.test(rel))) continue
  const { size } = await stat(file)
  bytes += size
  // Directory-style URLs: /brew/index.html is served as /brew/
  const path = rel.endsWith('/index.html') ? rel.slice(0, -'index.html'.length) : rel
  // Encode the path. Dynamic-route chunks live in directories like
  // `app/brew/[recipeId]/`, and webpack requests them as `%5BrecipeId%5D`.
  // Caching the raw bracket form means the cache never matches and the page
  // dies on hydration offline.
  assets.push(`${BASE}/${encodeURI(path)}`)
}

// A hash of the manifest becomes the cache name, so a new build swaps caches
// atomically and the old one is dropped on activate.
const version = createHash('sha256').update(assets.sort().join('\n')).digest('hex').slice(0, 12)

const sw = `/* Generated by scripts/build-sw.mjs. Do not edit. */
const BASE = ${JSON.stringify(BASE)}
const CACHE = 'extraction-${version}'
const PRECACHE = ${JSON.stringify(assets.sort(), null, 0)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE)
      // Individually, so one failed asset cannot abort the whole install.
      await Promise.all(
        PRECACHE.map((url) => cache.add(new Request(url, { cache: 'reload' })).catch(() => {})),
      )
      await self.skipWaiting()
    })(),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys()
      await Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n)))
      await self.clients.claim()
    })(),
  )
})

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  // Hashed build assets are immutable: cache first, never revalidate.
  if (url.pathname.startsWith(BASE + '/_next/static/')) {
    event.respondWith(
      (async () => {
        const hit =
          (await caches.match(request)) ??
          // Tolerate either encoding of bracketed dynamic-route directories.
          (await caches.match(encodeURI(decodeURI(url.pathname)))) ??
          (await caches.match(decodeURI(url.pathname)))
        if (hit) return hit
        return put(request, await fetch(request))
      })(),
    )
    return
  }

  // Pages: network first so a deploy is picked up, cache as the offline answer.
  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        try {
          const res = await fetch(request)
          return put(request, res)
        } catch {
          return (
            (await caches.match(request)) ??
            (await caches.match(withSlash(url.pathname))) ??
            (await caches.match(BASE + '/')) ??
            new Response('Offline and this page was never cached.', {
              status: 503,
              headers: { 'Content-Type': 'text/plain' },
            })
          )
        }
      })(),
    )
    return
  }

  // Everything else: serve cache, refresh in the background.
  event.respondWith(
    (async () => {
      const hit = await caches.match(request)
      const network = fetch(request)
        .then((res) => put(request, res))
        .catch(() => hit)
      return hit ?? network
    })(),
  )
})

function withSlash(pathname) {
  return pathname.endsWith('/') ? pathname : pathname + '/'
}

async function put(request, response) {
  if (response.ok && response.type === 'basic') {
    const cache = await caches.open(CACHE)
    cache.put(request, response.clone()).catch(() => {})
  }
  return response
}
`

await writeFile(join(OUT, 'sw.js'), sw, 'utf8')

// The manifest is a static file, so its absolute paths are patched here rather
// than duplicated as a build-time template.
const manifestPath = join(OUT, 'manifest.webmanifest')
const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
manifest.start_url = `${BASE}/`
manifest.scope = `${BASE}/`
manifest.icons = manifest.icons.map((icon) => ({
  ...icon,
  src: icon.src.startsWith(BASE) ? icon.src : `${BASE}${icon.src}`,
}))
await writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf8')

// Without this, GitHub Pages runs Jekyll, which silently ignores every
// directory beginning with an underscore — including all of /_next.
await writeFile(join(OUT, '.nojekyll'), '', 'utf8')

console.log(
  `service worker: ${assets.length} assets precached (${(bytes / 1024 / 1024).toFixed(2)} MB), cache extraction-${version}`,
)
console.log(`base path: ${BASE || '(root)'}  ·  wrote .nojekyll and patched manifest`)
